### PR TITLE
Issue#5

### PR DESCRIPTION
**Pull request by ghost**
Hello once again,

As discussed in #7, this should resolve issue #5. Now we should be able to define a comparator for the Set.

Cheers

### CODE REVIEW

**Comment by gkatsev** [comment]
Hello,
I really appreciate the work you've done. But I'm not sure I want to lose the simplicity that is available by having it backed by a regular object.
I am planning on (when I get around to it), change this so that it'll be backed by ES6's Set object instead, which would allow storing of actual objects rather than just strings and string representations of objects.

**Comment by ghost** [comment]
Hi,

No problem. May I be able to sway you?

Considering you don't want to change the storage type, I could change the code so that the internal object stores values like this:

**Proposition 1**

``` javascript
function add(object){
  this._storage[object]=object
}
```

This would put it in the user's hands to provide a `toString()` method, which creates a specific value. The only downside I see is the user would have to "pollute" their objects with `toString()`. That would make creating an array of custom objects... tedious or make the user to use `Array.map`.

**Proposition 2**  

``` javascript
function add(object){
  if( object == null) return;

  var type = typeof object;
  var string
  if(type != "object"){
    string = this._stringify(object)
  }else{
    string = object.toString()
  }
  this._storage[string]=object
}
```

This would allow the user to give the Set a `stringify` method. Thus they wouldn't need to change the objects the add to the set. We could even provide a default `stringify` method, which would simplify the code to:

``` javascript
Set = function (input, stringify){
  //...
  this._stringify = stringify || function(object){object.toString() }
}

function add(object){
  if( object == null) return;
  this._storage[this._stringify(string)]=object
}
```

**Comment by gkatsev** [comment]
I like option 1 more. And on top of that, rather than making them do a `toString()`, we should see if an incoming item is an object and then use `JSON.stringify` to get its string representation. Then they would need to override the `toJSON`, if they cared about a custom representation. Of course, this would only be needed if we aren't being backed by the real `Set`.

Also, I'm not opposed to having the backing object store a reference to the input directly.

**Comment by gkatsev** [comment]
If you make another PR, can you try and not making any whitespace changes? Thanks. :smile:

**Comment by gkatsev** [comment]
Also, thinking about it some more, if we do `JSON.stringify` objects, the comparator functionality isn't necessary because equivalent objects would get the same JSON output.

**Comment by ghost** [comment]
Indeed the "comparator" would be the object's key.

Once I have time again, I'll get about implementing option 1 :)

Cheers and thanks for the feedback!

**Comment by gkatsev** [comment]
Before you get started, you should check back again, I might implement it myself :D

**Comment by ghost** [comment]
I'll keep that in mind :)

**Pull request closed without merging**
